name: Operating System Abstraction Layer (OSAL) Tests

on:
  pull_request:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/**'
      - 'cmake_modules/**'
      - 'software/embedded_software/platform/operating_system_abstraction_layers/**'
    types:
      - opened
      - synchronize
    
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image from devcontainer
        run: |
          cd .devcontainer && docker build -t devcontainer-image:latest -f Dockerfile .
      - name: Configuring with preset x86-Debug-generic-linux
        run: |
          docker run --rm -v "$(pwd):/workspace" -w /workspace devcontainer-image:latest cmake --preset x86-Debug-generic-linux
      - name: Building with preset x86-Debug-generic-linux
        run: |
          docker run --rm -v "$(pwd):/workspace" -w /workspace devcontainer-image:latest cmake --build --preset x86-Debug-generic-linux
      - name: Testing with preset x86-Debug-generic-linux
        run: |
          docker run --rm --ulimit rtprio=99 -v "$(pwd):/workspace" -w /workspace devcontainer-image:latest ctest --test-dir build
      - name: Installing with preset x86-Debug-generic-linux
        run: |
          docker run --rm -v "$(pwd):/workspace" -w /workspace devcontainer-image:latest cmake --install build
        timeout-minutes: 1
